# Generated by Django 4.0.5 on 2022-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user',
            new_name='author',
        ),
    ]
