# Generated by Django 4.0.5 on 2022-06-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_desc'),
        ('cart', '0002_rename_user_shoppingcart_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to='product.product'),
        ),
    ]
