# Generated by Django 4.0.5 on 2022-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_choices',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Оплата картой'), ('debt', 'В рассрочку')], max_length=15),
        ),
    ]
